swcarpentry/make-novice

02-makefiles.md
* in 01-intro, some `.dat` and `.jpg` files were created, these need to be removed
* fixed small typo in a command
=> Small updates to 02-makefiles

index.md
I don't think saying the listed prerequisites 'would be useful' is enough. Students really need to be comfortable with the commands used in the exercise.
=> More strict prerequisite

03-variables.md
A mcq to test whether students understand what happens when one of the intermediate file sets gets updated
=> Add a multiple choice question to 03-variables

02-makefiles.md, 03-variables.md, 04-dependencies.md, 05-patterns.md, 07-functions.md
Addresses #5.
At several points (at the beginning or end of a lesson part), list the Makefile as it is at that point during the lesson for clarity, and for to make sure self-learners keep up.
=> At several places, list the content of the Makefile

07-functions.md
Adding a little explanation for the arguments of `patsubst.`
This Resolves https://github.com/swcarpentry/make-novice/issues/12
=> Add explanation for arguments of patsubst

09-solutions.html, 09-solutions.md, index.md
I don't know how useful this is because a lot of the solutions are presented within the lesson itself. I've added the solutions at the end of the "Other Resources" section of the lesson.
Partly addresses: https://github.com/swcarpentry/lesson-template/issues/267
=> Add solutions for make lesson

README.md
Moved "Please see" reference to the bottom.
=> Modified README.md for consistency with other lessons.

01-intro.md
For qualifying as an instructor of the Software Carpentry.
=> A little update about GNU Make comment.

01-intro.md
Incorporated one change to the lesson tried out at an intermediate
bioinformatics workshop.
Specifically, added a "master script" which runs the full analysis
pipeline described in the introduction.
Also added additional description of how a script like this
still fails to help when you make changes to your analysis.
=> Incorporated "master pipeline script" introduction from bsmith89/make-bml

04-dependencies.md, 06-variables.md, 08-self-doc.md
I've just worked through this lesson and spotted a few small errors. Further details in the commit messages.
=> Fixes typos and improves explanation of config.mk

setup.md
This addresses issue #60 rasied by njmescouk
=> Added list of required software to setup.md

_extras/discuss.md
Addresses issue #75
This is for instructor-training.
=> Added discussion of make variables, shell variables, and quoting

_extras/guide.md
As discussed in #99 I publish here my workaround in case the problem pops up somewhere else. It seems that this OS is not mainstream but just in case.
=> add troubleshooting guide for UnicodeDecodeError; fixes #99

_episodes/09-conclusion.md, code/09-conclusion-challenge-2/Makefile
In the final example Makefile:
1) includes the Makefile configuration file, config.mk, in the project archive
2) adds additional dependencies to ensure that the archive is updated when analysis files are updated
=> Improvements to dependencies in Makefile

CONTRIBUTING.md
The CONTRIBUTING.md file sported a FIXME url instead of the correct one. This PR fixes it.
=> fixed the url in CONTRIBUTING.md

_episodes/04-dependencies.md, _episodes/09-conclusion.md, code/09-conclusion-challenge-2/Makefile
Changing the text of the archiving exercise in the conclusion chapter 09 and changing the solution makefile for that exercise.  The changes address issue #105.  
There is still a problem in my solution:  the books directory in the archive does not include the license file that goes with the books txt files.
=> Changes to second exercise in 09 issue #105

_episodes/01-intro.md
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
=> correct tiny typo

_episodes/06-variables.md
Eliminating repeated content is the main motivator for me.
Being able to change the implementation is more of a bonus.
Addresses some of the discussion on #120.
=> Reword motivation for COUNT_EXE variable

_episodes/06-variables.md, _episodes/07-functions.md, code/06-variables-challenge/Makefile, code/06-variables/config.mk, code/07-functions/config.mk, code/08-self-doc/config.mk, code/09-conclusion-challenge-1/config.mk, code/09-conclusion-challenge-2/config.mk
Fix #129.
Propagate changes through the rest of the lesson.
=> Use variable for python

_episodes/01-intro.md, _episodes/02-makefiles.md, _episodes/03-variables.md, _episodes/04-dependencies.md, _episodes/05-patterns.md, _episodes/06-variables.md, _episodes/07-functions.md, _episodes/08-self-doc.md, _episodes/09-conclusion.md
=> Update episode timings

_episodes/01-intro.md, _episodes/02-makefiles.md, _episodes/03-variables.md, _episodes/04-dependencies.md, _episodes/05-patterns.md, _episodes/06-variables.md, _episodes/07-functions.md, _episodes/08-self-doc.md, _episodes/09-conclusion.md
=> Use updated syntax highlighting for code blocks

_extras/discuss.md, setup.md
Fixes to a broken link in the discussion and an updated link to Anaconda.
=> Fix to broken links

README.md, _episodes/01-intro.md, _episodes/02-makefiles.md, _episodes/03-variables.md, _episodes/04-dependencies.md, _episodes/06-variables.md, _episodes/07-functions.md, _episodes/09-conclusion.md, _extras/discuss.md, _extras/guide.md, reference.md, setup.md
I have worked through the documents of the make-novice lesson and have some small fixes to improve the pages and Markdown source code. Please have a look at my changes and check if they could be merged into your upstream repository. Maybe it would be best to squash the commits to one commit before merging, but for the sake of completeness I have kept them separate to be able to trace the changes I have made.
=> Some small fixes

_episodes/04-dependencies.md, _episodes/05-patterns.md, _episodes/06-variables.md, _episodes/07-functions.md, _episodes/08-self-doc.md, code/04-dependencies/Makefile, code/05-patterns/Makefile, code/06-variables-challenge/Makefile, code/06-variables/Makefile, code/06-variables/config.mk, code/07-functions/Makefile, code/07-functions/config.mk, code/09-conclusion-challenge-1/Makefile, code/09-conclusion-challenge-1/config.mk, code/09-conclusion-challenge-2/Makefile, code/09-conclusion-challenge-2/config.mk
Currently a work in progress. I need to think about how to modifiy/reorder the variables/ functions episodes because currently the variables episode is no longer compatible with this PR
Fix #166
=> Automatic variables
