- 07-functions.md
* add clarification to put variable declaration at the beginning of the makefile
* changed 'processed' to 'included' for `sierra.txt` first time it mentioned
* added note about processing of `sierra.txt`
> Small updates to 07-functions

- 02-makefiles.md
Typo: change `books/isles.dat` to `books/isles.txt` (the dependency)
Add `books` path to `isles.txt` for clarity.
> Small changes (typo) to 02-makefiles

- 04-dependencies.md
`04-dependencies` references the file `workflow.py` but should reference `wordcount.py`. This pull request fixes the typo.
> Fix "workflow.py" typo in 04-dependencies.md

- index.md
I understand that we want to show that Make could be used for many kinds of task, but I believe its primary usage, especially for Software Carpentry, is for building programs.
https://en.wikipedia.org/wiki/Make_%28software%29
I emphasized the "make" Unix command instead of Unix Shell's Make.
I wrote "summarize" instead of "summarise".
> Software development first, generic usage second

- 05-patterns.md
- 07-functions.md
- code/samples/05-patterns/Makefile
- code/samples/06-variables-challenge/Makefile
- code/samples/06-variables/Makefile
- code/samples/07-functions/Makefile
- code/samples/08-conclusion-challenge/Makefile
- reference.md
- solutions.md
To replace $@. In my opinion, it is more readable using $*.dat than $@. The additional information ".dat" makes it clear that this is the target that we intend to generate.
> Added the use of the automatic variable $*

- 02-makefiles.md
I thought this might be a little confusing since the name of the Makefile wasn't changed when using the `-f` option, but now it's not an example that could be run. It's probably not instructive to rename the Makefile, or maybe it would be since then it wouldn't run with `make` and no arguments.
> Clarify -f option

- _episodes/02-makefiles.md
It makes slightly more sense to introduce this callout _after_ it has been shown one can use the `make` command with a specific target.
> Move callout on Make message slightly down

- _episodes/04-dependencies.md
Figure 04-dependencies.png and the corresponding makefile in code/04-dependencies/ both have the `zipf_test.py` script as dependency to the `results.txt` file, but the lesson does not describe this addition. This PR fixes that.
> Add zipf_test script as dependency too

- _episodes/07-functions.md
Adds an exercise I successfully used when I taught the lesson: get another book from the Project Gutengberg website and add it to the `books` folder. Demonstrates the power of the dependency tree and mirrors real life as data sometimes comes in incrementally.
> Add more books exercise

- code/09-conclusion-challenge-2/Makefile
Remove unnecessary $(RESULTS_TXT) variable in code/09-conclusion-challenge-2/Makefile, line 17
> Remove unnecessary variable in 09/conclusion-challenge-2/Makefile

- _episodes/04-dependencies.md
- _episodes/05-patterns.md
- _episodes/07-functions.md
- code/04-dependencies/Makefile
- code/05-patterns/Makefile
- code/06-variables-challenge/Makefile
- code/06-variables/Makefile
This pull request addresses two issues with Challenge: `wordcount` as a Dependency of `results.txt` (http://swcarpentry.github.io/make-novice/04-dependencies/):
1. The focus of the exercise should be on adding `zipf_test.py` as a depenedency of `results.txt`, not `wordcount.py`. The problem that students are expected to identify in the challenge remains unchanged.
2. When adding `zipf_test.py`, the lesson suggests replacing `$^` with `$<` i,e:
```
results.txt : *.dat zipf_test.py
python zipf_test.py $< > $@
```
But this is a bug since it means that only the first `.dat` file will ever be added to `results.txt`. This can be seen by using `code/04-dependencies/Makefile`:
```
$ make dats
python wordcount.py books/isles.txt isles.dat
python wordcount.py books/abyss.txt abyss.dat
python …
```
> Fix two issues with Challenge: `wordcount` as a Dependency of `results.txt`.

- _episodes/04-dependencies.md
- _episodes/09-conclusion.md
Episode-04 Changed dash in file name to underscore to match file names in code.  Episode 09: changed misspelling of conforms.
> Fixing minor typos

- _episodes/02-makefiles.md
- _episodes/03-variables.md
- _episodes/04-dependencies.md
- _episodes/05-patterns.md
- _episodes/07-functions.md
- _episodes/08-self-doc.md
The example Makefile in episode 2 uses spaces instead of tab. There is a not about this later on, but I think it makes sense to fix this in example as well. Also, this is part of instructor training checkout.
> convert space to tab

- _episodes/02-makefiles.md
- _episodes/03-variables.md
- _episodes/04-dependencies.md
- _episodes/05-patterns.md
- _episodes/06-variables.md
- _episodes/07-functions.md
- _episodes/09-conclusion.md
Updates all links to the reference page so that they no longer produce a "404: File not found" error when clicked
> Change links '/reference/#...' to '/reference#...'

- _episodes/07-functions.md
- _episodes/08-self-doc.md
- code/07-functions/Makefile
- code/08-self-doc/Makefile
- code/09-conclusion-challenge-1/Makefile
- code/09-conclusion-challenge-2/Makefile
Fix #128.
Previous makefile has this rule:
results.txt : $(ZIPF_SRC) isles.dat abyss.dat last.dat
This then gets rewritten as
results.txt : $(DAT_FILES) $(ZIPF_SRC)
but there's no good reason to reorder the dependencies, so I'm
replacing the explicit dependencies with a variable in the same order:
results.txt : $(ZIPF_SRC) $(DAT_FILES)
My hope it that this makes the lesson easier to follow.
> Un-reorder dependencies of results.txt

- code/plotcounts.py
- code/testzipf.py
I kept getting an error when running `python plotcounts.py isles.dat ascii` in the intro lesson, saying `ImportError: cannot import name 'load_word_counts'`. 
I realized the python filenames must have changed at some point, from `wordcount.py` to `countwords.py`, but the import in `plotcounts.py` still used the old `wordcount`. I updated the name and the script worked fine.
> updated 'wordcount' to 'countwords' in `plotcounts.py`

- code/plotcounts.py
To keep the lesson working in Python >= 3.8, import `Sequence`
from `collections.abc` rather than from `collections`. For compatibility,
use try/except to import from `collections` in earlier versions of Python.
Avoids a deprecation warning when running through the lesson with Python 3.7.
For details on collections.abc vs collections, see [this Stack Overflow question](https://stackoverflow.com/q/55882715).
> Future-proof import of Sequence in plotcounts.py

- _episodes/06-variables.md
For consistency with the rest of the lesson.
> Rename zipf-test.py to testzipf.py in episode 6

- _extras/guide.md
It is very rare, but on some systems gmake needs to be used instead of make. 
This is a follow up change suggestion: https://github.com/swcarpentry/make-novice/issues/153
> Update guide.md with make/gmake remark

- _episodes/07-functions.md
Project Gutenberg seems to have changed the format of how they indicate the beginning and end of a text file. See e.g. the Picture of Dorian Gray example as suggested in the lesson. (Same holds for other books.)
(Thank you for a great tutorial!)
> Update the Gutenberg string
